version: '3'
services:
    mssql:
      build: Docker
      image: nuitsjp/wpf-architecture-2022:latest
      container_name: SQL-Server
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssw0rd!
